---
openapi: 3.0.3
info:
  title: Geolocation API
  version: 1.2.1
servers: []
paths:
  "/api/v1/geolocations":
    get:
      summary: index
      tags:
      - API::V1::Geolocation
      responses:
        '200':
          description: returns paginated results with links
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            ip:
                              type: string
                            host:
                              type: string
                            country:
                              type: string
                            city:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            provider:
                              type: string
                          required:
                          - ip
                          - host
                          - country
                          - city
                          - latitude
                          - longitude
                          - provider
                      required:
                      - id
                      - type
                      - attributes
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        nullable: true
                      next:
                        type: string
                        nullable: true
                    required:
                    - first
                    - last
                    - prev
                    - next
                required:
                - data
                - links
              example:
                data:
                - id: '1536'
                  type: geolocation
                  attributes:
                    ip: 241.211.193.85
                    host: google.com
                    country: Lithuania
                    city: Yundtfurt
                    latitude: '86.69052927057632'
                    longitude: "-128.2052896025566"
                    provider: IPSTACK
                - id: '1537'
                  type: geolocation
                  attributes:
                    ip: 228.27.199.97
                    host: google.com
                    country: Latvia
                    city: Lake Shelia
                    latitude: '78.60067424027793'
                    longitude: '103.658934637387'
                    provider: IPSTACK
                - id: '1538'
                  type: geolocation
                  attributes:
                    ip: 123.209.215.210
                    host: google.com
                    country: Guatemala
                    city: Reyesshire
                    latitude: "-18.4907317856359"
                    longitude: '20.77558341203482'
                    provider: IPSTACK
                - id: '1539'
                  type: geolocation
                  attributes:
                    ip: 230.100.153.80
                    host: google.com
                    country: Zimbabwe
                    city: Sonnytown
                    latitude: '88.97612565018159'
                    longitude: "-137.1695118629437"
                    provider: IPSTACK
                - id: '1540'
                  type: geolocation
                  attributes:
                    ip: 247.101.226.175
                    host: google.com
                    country: Virgin Islands, British
                    city: Leannonhaven
                    latitude: '37.87999145675589'
                    longitude: '101.7802783799495'
                    provider: IPSTACK
                links:
                  first: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=1&page%5Blimit%5D=5"
                  last: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=2&page%5Blimit%5D=5"
                  prev:
                  next: "/api/v1/geolocations?ip_or_host=google.com&page%5Bpage%5D=2&page%5Blimit%5D=5"
        '400':
          description: returns 400 bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Query parameter is required (should be IP or Host)
      parameters:
      - name: ip_or_host
        in: query
        required: false
        schema:
          type: string
        example: google.com
      security:
      - Authorization: []
    post:
      summary: create
      tags:
      - API::V1::Geolocation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                geolocation:
                  type: object
                  properties:
                    ip_or_host:
                      type: string
                  required:
                  - ip_or_host
              required:
              - geolocation
            example:
              geolocation:
                ip_or_host: google.com
      responses:
        '201':
          description: returns success and creates new geolocation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          ip:
                            type: string
                          host:
                            type: string
                          country:
                            type: string
                          city:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                          provider:
                            type: string
                        required:
                        - ip
                        - host
                        - country
                        - city
                        - latitude
                        - longitude
                        - provider
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '1548'
                  type: geolocation
                  attributes:
                    ip: 175.2.112.230
                    host: google.com
                    country: United States
                    city: Chicago
                    latitude: '10.0'
                    longitude: '11.1'
                    provider: IPSTACK
        '400':
          description: returns unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        ip:
                          type: array
                          items:
                            type: string
                        country:
                          type: array
                          items:
                            type: string
                        city:
                          type: array
                          items:
                            type: string
                        latitude:
                          type: array
                          items:
                            type: string
                        longitude:
                          type: array
                          items:
                            type: string
                      required:
                      - ip
                      - country
                      - city
                      - latitude
                      - longitude
                required:
                - errors
              example:
                errors:
                - ip:
                  - must be a valid IPv4 or IPv6 address
                  country:
                  - can't be blank
                  city:
                  - can't be blank
                  latitude:
                  - can't be blank
                  longitude:
                  - can't be blank
      security:
      - Authorization: []
  "/api/v1/geolocations/{id}":
    delete:
      summary: destroy
      tags:
      - API::V1::Geolocation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1546
      responses:
        '204':
          description: returns no content and destroys geolocation
        '404':
          description: returns 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Resource not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example: {}
      security:
      - Authorization: []
    get:
      summary: show
      tags:
      - API::V1::Geolocation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        example: dummy
      responses:
        '200':
          description: returns successfully single resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          ip:
                            type: string
                          host:
                            type: string
                          country:
                            type: string
                          city:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                          provider:
                            type: string
                        required:
                        - ip
                        - host
                        - country
                        - city
                        - latitude
                        - longitude
                        - provider
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '1505'
                  type: geolocation
                  attributes:
                    ip: 63.161.33.94
                    host: http://pacocha.test/bernardo
                    country: Sudan
                    city: Kesslerton
                    latitude: "-84.71726128166856"
                    longitude: '13.18728202683232'
                    provider: IPSTACK
        '404':
          description: returns 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Resource not found
      security:
      - Authorization: []
components:
  securitySchemes:
    Authorization:
      description: Authenticate API requests via API Token
      in: header
      scheme: apiKey
      type: apiKey
      name: Authorization
